version: "3.4"

services:
  pingaccess:
    image: pingidentity/pingaccess:6.2.1-edge
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=getting-started/pingaccess
    env_file:
      - ~/.pingidentity/devops
      - variables.env
    # Example: Examples below for mounting local directories for inbound server profile and persisting
    #          server build.  The local /opt/out directory must be empty when building new server
    #             /opt/out - Resulting server build
    #             /opt/in  - Inbound server-profile detail in liue of SERVER_PROFILE_URL (must be commented out)
    #volumes:
    #   - ${HOME}/projects/devops/volumes/full-stack.pingaccess:/opt/out
    #   - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingaccess:/opt/in
    ports:
      - 443:3000
      - 9000:9000
    expose:
      - 443
      - 9000
#    volumes:
#      - ./licenses/pingaccess.lic:/opt/in/instance/conf/pingaccess.lic
    networks:
      - pingnet-internal

  pingfederate:
    image: pingidentity/pingfederate:10.2.2-edge
    environment:
#      - LICENSE_DIR=/opt/in/instance/server/default/conf
#      - LICENSE_FILE_NAME=pingfederate.lic
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=getting-started/pingfederate
      - SERVER_PROFILE_PARENT=EDPOC
      - SERVER_PROFILE_EDPOC_URL=https://github.com/ttranatping/ed_poc.git
      - SERVER_PROFILE_EDPOC_PATH=server_profiles/pingfederate
    env_file:
      - ~/.pingidentity/devops
      - variables.env
    ports:
      - 9031:9031
      - 9999:9999
    networks:
      - pingnet-internal
    cap_add:
      - NET_ADMIN

networks:
    pingnet-internal:
